//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Addresses struct {
	Postcode     *string
	HouseNumber  *int32
	Addition     *string
	Extension    *string
	Municipality *string
	City         *string
	Street       *string
	LongStreet   *string
	ShortStreet  *string
	Area         *float32
	Usage        *string
	BuiltIn      *int32
	Latitude     *float32
	Longitude    *float32
}
