service: postcode

image: ghcr.io/maantje/postcode

servers:
  - postcode.j4mie.com

proxy:
  host: postcode.j4mie.com
  ssl: true
  healthcheck:
    path: /docs

registry:
  server: ghcr.io
  username: maantje
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: arm64
